CREATE TABLE IF NOT EXISTS configuration (
    "_id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "email" TEXT,
    "emailName" TEXT,
    "password" TEXT,
    "enableEmail" BOOLEAN DEFAULT FALSE,
    "clientId" TEXT,
    "clientSecret" TEXT,
    "sandbox" BOOLEAN DEFAULT TRUE,
    "publishableKey" TEXT,
    "secretKey" TEXT,
    "currency" TEXT DEFAULT 'USD',
    "currencySymbol" TEXT DEFAULT '$',
    "deliveryRate" NUMERIC DEFAULT 5.0,
    "twilioAccountSid" TEXT,
    "twilioAuthToken" TEXT,
    "twilioPhoneNumber" TEXT,
    "twilioEnabled" BOOLEAN DEFAULT FALSE,
    "skipWhatsAppOTP" BOOLEAN DEFAULT TRUE,
    "twilioWhatsAppNumber" TEXT,
    "formEmail" TEXT,
    "sendGridApiKey" TEXT,
    "sendGridEnabled" BOOLEAN DEFAULT FALSE,
    "sendGridEmail" TEXT,
    "sendGridEmailName" TEXT,
    "sendGridPassword" TEXT,
    "dashboardSentryUrl" TEXT,
    "webSentryUrl" TEXT,
    "apiSentryUrl" TEXT,
    "customerAppSentryUrl" TEXT,
    "restaurantAppSentryUrl" TEXT,
    "riderAppSentryUrl" TEXT,
    "googleApiKey" TEXT,
    "cloudinaryUploadUrl" TEXT,
    "cloudinaryApiKey" TEXT,
    "webAmplitudeApiKey" TEXT,
    "appAmplitudeApiKey" TEXT,
    "webClientID" TEXT,
    "androidClientID" TEXT,
    "iOSClientID" TEXT,
    "expoClientID" TEXT,
    "googleMapLibraries" TEXT,
    "googleColor" TEXT,
    "termsAndConditions" TEXT,
    "privacyPolicy" TEXT,
    "testOtp" BOOLEAN DEFAULT TRUE,
    "firebaseKey" TEXT,
    "authDomain" TEXT,
    "projectId" TEXT,
    "storageBucket" TEXT,
    "msgSenderId" TEXT,
    "appId" TEXT,
    "measurementId" TEXT,
    "isPaidVersion" BOOLEAN DEFAULT FALSE,
    "skipEmailVerification" BOOLEAN DEFAULT TRUE,
    "skipMobileVerification" BOOLEAN DEFAULT TRUE,
    "costType" TEXT DEFAULT 'fixed',
    "vapidKey" TEXT
);

INSERT INTO configuration ("_id", "email", "currency", "currencySymbol")
VALUES (uuid_generate_v4(), 'admin@enatega.com', 'USD', '$');
